### ISSUE TITLE
build fails [Failed to take the filesystem lock on /usr/share/vcpkg/.vcpkg-root] results in [CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage]

### ISSUE THREAD

**Issue by ericfont** [ericfont/fibo-vcpkg-example#1]
`cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=/usr/share/vcpkg/scripts/buildsystems/vcpkg.cmake`
```
-- Running vcpkg install
Failed to take the filesystem lock on /usr/share/vcpkg/.vcpkg-root:
    Permission denied
-- Running vcpkg install - failed
CMake Error at /usr/share/vcpkg/scripts/buildsystems/vcpkg.cmake:829 (message):
  vcpkg install failed.  See logs for more information:
  /home/e/fibo-vcpkg-example/build/vcpkg-manifest-install.log
Call Stack (most recent call first):
  /usr/share/cmake-3.21/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:3 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

**Comment by ericfont** [comment]
I found a work around to perpend the `cmake` command with `sudo`, like:

`sudo cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=/usr/share/vcpkg/scripts/buildsystems/vcpkg.cmake`

that way vcpkg can get a filesystem lock on `/usr/share/vcpkg/.vcpkg-root`, which is necessary for modifying the packages `vcpkg-cmake[core]` and `vcpkg-cmake-config[core]` to the system:
```
-- Running vcpkg install
Detecting compiler hash for triplet x64-linux...
The following packages will be built and installed:
    cxxopts[core]:x64-linux -> 2.2.1#1
    fmt[core]:x64-linux -> 8.0.1
    range-v3[core]:x64-linux -> 0.11.0#1
  * vcpkg-cmake[core]:x64-linux -> 2021-09-13
  * vcpkg-cmake-config[core]:x64-linux -> 2021-09-27
Additional packages (*) will be modified to complete this operation.
Restored 5 packages from /root/.cache/vcpkg/archives in 51.71 ms. Use --debug to see more details.
Starting package 1/5: cxxopts:x64-linux
Installing package cxxopts[core]:x64-linux...
Elapsed time for package cxxopts:x64-linux: 911.3 us
Starting package 2/5: vcpkg-cmake-config:x64-linux
Installing package vcpkg-cmake-config[core]:x64-linux...
Elapsed time for package vcpkg-cmake-config:x64-linux: 535.9 us
Starting package 3/5: vcpkg-cmake:x64-linux
Installing package vcpkg-cmake[core]:x64-linux...
Elapsed time for package vcpkg-cmake:x64-linux: 784.8 us
Starting package 4/5: fmt:x64-linux
Installing package fmt[core]:x64-linux...
Elapsed time for package fmt:x64-linux: 3.999 ms
Starting package 5/5: range-v3:x64-linux
Installing package range-v3[core]:x64-linux...
Elapsed time for package range-v3:x64-linux: 18.18 ms

Total elapsed time: 76.18 ms

The package cxxopts provides CMake targets:

    find_package(cxxopts CONFIG REQUIRED)
    target_link_libraries(main PRIVATE cxxopts::cxxopts)

The package fmt provides CMake targets:

    find_package(fmt CONFIG REQUIRED)
    target_link_libraries(main PRIVATE fmt::fmt)

    # Or use the header-only version
    find_package(fmt CONFIG REQUIRED)
    target_link_libraries(main PRIVATE fmt::fmt-header-only)

The package range-v3 provides CMake targets:

    find_package(range-v3 CONFIG REQUIRED)
    # Note: 2 target(s) were omitted.
    target_link_libraries(main PRIVATE range-v3 range-v3-meta range-v3::meta range-v3-concepts)

-- Running vcpkg install - done
-- The CXX compiler identification is GNU 11.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/e/fibo-vcpkg-example/build
```

But using `sudo` inside build scripts is generally not a good practice, and using sudo for cmake results in my local project's entire build directly being owned by the root user.  So I started a discussion at https://github.com/microsoft/vcpkg/discussions/20541 for vcpkg to have a better user privilege practice.

**Comment by ericfont** [comment]
answered by https://github.com/microsoft/vcpkg/discussions/20541

Solution is to not install vcpkg via arch package manager to a system root folder.  Instead just save locally.

**Comment by Eshanatnight** [comment]
Hi,

I just cloned the vcpkg repo, ran [bootstrap-vcpkg.sh](https://github.com/microsoft/vcpkg/blob/master/bootstrap-vcpkg.sh) script.

added the binary to the path. 

ran cmake 

```zsh
-- Running vcpkg install
Failed to take the filesystem lock on /home/kellsatnite/tools/vcpkg/.vcpkg-root:
    Permission denied
-- Running vcpkg install - failed
CMake Error at /home/kellsatnite/tools/vcpkg/scripts/buildsystems/vcpkg.cmake:829 (message):
  vcpkg install failed.  See logs for more information:
  /home/kellsatnite/dev/plus/build/vcpkg-manifest-install.log
.
.
.
```
---
I deleted the vcpkg repo. Then re cloned vcpkg, in the same location, ran `bootstrap-vcpkg.sh`. 
Then ran `vcpkg integrate install`. Then ran cmake. But still got the same error.

Any clue or ideas on what to do or whatever I should do. 

I only had ***cmake*** installed from the AUR. And the ***GCC/G++*** was there in the Install from the get go.

OS: Arch

**Comment by ericfont** [comment]
I'm sorry I actually have no idea, because I am merely a forker of this project and was trying to get things to work, so you should ask upstream for help.

**Comment by Eshanatnight** [comment]
No problem, I figured it out!

**Comment by filipe-varela** [comment]
Can you explain what you did please? @Eshanatnight

**Comment by Eshanatnight** [comment]
It's super embarrassing. I downloaded vcpkg in the root rather than in the home directory. So whenever I was going to run integrate install, It would freak out.
Just rm -rf the current cloned vcpkg instance, and re clone it somewhere in the home directory. It should work fine then. @filipe-varela

**Comment by filipe-varela** [comment]
@Eshanatnight ah that's what I did, thanks xp

**Comment by Skwangles** [comment]
Alternatively what worked for me was just CHOWN it -  `sudo chown -R $USER:$USER <dir>/vcpkg`
The installation thing I read got me to put it in `/opt/vcpkg` which is obviously not owned by the user
